
language: python
python:
  - "3.6"
install:
  - pip install -r ./requirements.txt
script: 
  - python manage.py test --verbosity=2
  - coverage run --source=api manage.py test
after_success:
  coveralls